backend:
  name: git-gateway
  repo: RedCiudadana/Web_Giz
  branch: main
  identity_url: https://auth.decapbridge.com/sites/809ca86c-8f45-409c-95fd-c7bbeef1211d
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
- name: "talleres"
  label: "Talleres"
  folder: "src/content/talleres"
  create: true
  slug: "{{slug}}"
  fields:
    - { label: "Título", name: "title", widget: "string" }
    - { label: "Fecha", name: "fecha", widget: "datetime", date_format: "DD [de] MMMM [de] YYYY", time_format: false }
    - { label: "Tipo de evento", name: "tipo", widget: "select", options: ["Workshop", "Webinar", "Conference"] }
    - { label: "Ubicación", name: "ubicacion", widget: "string" }
    - { label: "Estado", name: "estado", widget: "select", options: ["Próximo", "Pasado"] }
    - { label: "Texto del botón", name: "boton_texto", widget: "select", options: ["Inscribirse", "Ver recursos"] }
    - { label: "Link del botón", name: "link", widget: "string", required: false }
